CREATE DATABASE warehouse_db;
USE warehouse_db;

CREATE TABLE artifacts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  origin VARCHAR(100),
  time_frame VARCHAR(100),
  current_location VARCHAR(100)
);

INSERT INTO artifacts (name, origin, time_frame, current_location)
VALUES
  ('Lewis Carroll''s Looking Glass', 'Inspired by Lewis Carroll''s Through the Looking-Glass and Alice''s adventures.', 'Late 19th century', 'Aisle 7 Shelf 3'),
  ('H.G. Well''s Time Machine', 'Based on the concept of the time machine from H.G. Well''s novel The Time Machine.', 'Late 19th century', 'Aisle 12 Shelf 6'),
  ('Edgar Allan Poe''s Quill Pen', 'Associated with the renowned writer Edgar Allan Poe.', '19th century', 'Aisle 4 Shelf 2'),
  ('Alice Liddell''s Mirror Connected to Alice Liddell', 'who inspired Lewis Carroll''s Alice''s Adventures in Wonderland.', '19th century', 'Aisle 8 Shelf 1'),
  ('The Astrolabe', 'Originates from ancient civilizations.', 'Ancient history', 'Aisle 3 Shelf 5'),
  ('The Aztec Bloodstone', 'Connected to the Aztec civilization.', 'Ancient history', 'Aisle 10 Shelf 4'),
  ('Nikola Tesla''s Electrostatic Cannon', 'Invented by renowned scientist Nikola Tesla.', 'Late 19th to early 20th century', 'Aisle 5 Shelf 8'),
  ('The Philosopher''s Stone', 'Linked to alchemical practices and legends.', 'Ancient history', 'Aisle 1 Shelf 9'),
  ('The Harmonic Convergence Gauntlet', 'Created by ancient civilizations.', 'Ancient history', 'Aisle 9 Shelf 7'),
  ('The Tunguska Blast Fragments', 'Related to the Tunguska event in 1908.', 'Early 20th century', 'Aisle 2 Shelf 4'),
  ('Alexander the Great''s Helmet', 'Associated with the legendary conqueror Alexander the Great.', '4th century BCE', 'Aisle 11 Shelf 3'),
  ('The Eye of Odin', 'Connected to the Norse god Odin.', 'Ancient Norse mythology', 'Aisle 4 Shelf 7'),
  ('The Shroud of Turin', 'Believed to be the burial cloth of Jesus Christ.', '1st century CE', 'Aisle 8 Shelf 5'),
  ('Marie Curie''s Radium Flask', 'Associated with renowned scientist Marie Curie.', 'Late 19th to early 20th century', 'Aisle 12 Shelf 2'),
  ('The Scepter of Cleopatra', 'Connected to the last pharaoh of Egypt, Cleopatra.', '1st century BCE', 'Aisle 3 Shelf 8'),
  ('The Invisible Cloak of Merlin', 'Believed to be connected to the legendary wizard Merlin.', 'Mythical timeframe (Arthurian legend)', 'Aisle 7 Shelf 1'),
  ('The Rosetta Stone', 'An ancient Egyptian artifact with inscriptions in multiple languages.', 'Ancient history (196 BCE)', 'Aisle 2 Shelf 6'),
  ('Isaac Newton''s Apple', 'Linked to the story of Sir Isaac Newton and the discovery of gravity.', '17th century', 'Aisle 10 Shelf 2'),
  ('The Ghostly Gramophone', 'Early recording device imbued with supernatural properties.', 'Late 19th to early 20th century', 'Aisle 5 Shelf 3'),
  ('The Crystal Skull of Mesoamerica', 'Associated with ancient Mesoamerican civilizations.', 'Ancient history', 'Aisle 9 Shelf 1'),
  ('Leonardo da Vinci''s Flying Machine', 'Designed by the famous artist and inventor Leonardo da Vinci.', '15th century', 'Aisle 11 Shelf 5'),
  ('The Sword of Joan of Arc', 'Linked to the French heroine Joan of Arc.', '15th century', 'Aisle 1 Shelf 7'),
  ('The Serpent''s Crown', 'Associated with various ancient serpent-related legends.', 'Varied, from ancient civilizations to mythological eras', 'Aisle 6 Shelf 3'),
  ('The Lunar Rock Sample', 'Collected from the moon during a space mission.', '20th century (specific mission dependent)', 'Aisle 8 Shelf 4'),
  ('The Spirit Radio', 'Experimental radio device for communication with the spirit realm.', 'Late 19th to early 20th century', 'Aisle 2 Shelf 9'),
  ('The Atlantean Crystal', 'Linked to the mythical civilization of Atlantis.', 'Mythical timeframe', 'Aisle 12 Shelf 3'),
  ('The Elixir of Life', 'Legends and alchemical practices.', 'Various throughout history', 'Aisle 4 Shelf 3'),
  ('The Gravity Boots of Sir Isaac Newton', 'Inspired by Sir Isaac Newton''s studies on gravity.', '17th century', 'Aisle 7 Shelf 5'),
  ('The Hypnotic Pocket Watch', 'Used for hypnotic inductions and mind control.', 'Late 19th to early 20th century', 'Aisle 3 Shelf 4'),
  ('The Enigma Machine', 'A cipher machine used during World War II.', '20th century', 'Aisle 10 Shelf 6'),
  ('The X-Ray Specs', 'Early x-ray technology and optical illusions.', 'Early 20th century', 'Aisle 5 Shelf 1'),
  ('The Crystal Ball of Nostradamus', 'Associated with the renowned seer Nostradamus.', '16th century', 'Aisle 9 Shelf 8'),
  ('The Microbot Swarm', 'Advanced nanotechnology.', 'Modern era', 'Aisle 1 Shelf 3'),
  ('The Etruscan Cursed Ring', 'Linked to the ancient Etruscan civilization.', 'Ancient history', 'Aisle 6 Shelf 5'),
  ('The Ghostly Typewriter', 'Early typewriter imbued with paranormal abilities.', 'Late 19th to early 20th century', 'Aisle 8 Shelf 2'),
  ('The Mirror of Eratosthenes', 'Named after the ancient Greek mathematician Eratosthenes.', 'Ancient history', 'Aisle 2 Shelf 5'),
  ('The Luminescent Butterfly', 'A rare species of butterfly with bioluminescent properties.', 'Varied (existed for centuries)', 'Aisle 11 Shelf 4'),
  ('The Singularity Core', 'Prototype energy source related to theoretical physics.', 'Modern era', 'Aisle 4 Shelf 8'),
  ('The Hypersonic Sound Wave Generator', 'Experimental sound technology.', 'Modern era', 'Aisle 7 Shelf 2'),
  ('The Vitruvian Man Blueprint', 'Inspired by Leonardo da Vinci''s famous Vitruvian Man drawing.', '15th century', 'Aisle 3 Shelf 6'),
  ('The Neural Interface Helmet', 'Experimental brain-computer interface device.', 'Modern era', 'Aisle 10 Shelf 3'),
  ('The Enchanted Fountain Pen', 'Magical pen that brings drawings to life.', 'Ancient history', 'Aisle 5 Shelf 4'),
  ('The Zero-Gravity Shoes', 'Experimental footwear for simulated weightlessness.', 'Modern era', 'Aisle 9 Shelf 7'),
  ('The Paradox Hourglass', 'Time-altering hourglass with unpredictable effects.', 'N/A (related to time manipulation)', 'Aisle 1 Shelf 8'),
  ('The Levitating Globe', 'A globe that defies gravity and floats in mid-air.', 'Modern era', 'Aisle 6 Shelf 1'),
  ('The Chaos Crystal', 'Ancient gem associated with chaos and unpredictability.', 'Ancient history', 'Aisle 8 Shelf 7'),
  ('The Whispering Seashell', 'Seashell that allows communication over long distances.', 'Varied (existed for centuries)', 'Aisle 2 Shelf 3'),
  ('The Molecular Manipulator', 'Advanced device capable of manipulating matter at the molecular level.', 'Modern era', 'Aisle 11 Shelf 2'),
  ('The Quantum Entanglement Earrings', 'Earrings that establish a quantum entanglement connection between wearers.', 'Modern era', 'Aisle 4 Shelf 6'),
  ('The Celestial Compass', 'Ancient navigational instrument used to track celestial bodies.', 'Ancient history', 'Aisle 10 Shelf 6');